### PR TITLE
Use "external_links" (array of URLs) rather than "external_tickets"

### PR DESCRIPTION
**Pull request by etipton**
Addresses: #22 

~(untested)~ tested.

### CODE REVIEW

**Comment by etipton** [comment]
This "worked" but note that it created an "external link" like:

image

rather than adding something under the "Pull Requests" section like:

image

(which is still better than nothing IMO)

**Comment by singingwolfboy** [comment]
Looks good to me! I haven't tested this myself, but I've verified that the Clubhouse API documentation supports this change. If you say you've tested it, that's good enough for me!

**Comment by etipton** [comment]
> Looks good to me! I haven't tested this myself, but I've verified that the Clubhouse API documentation supports this change. If you say you've tested it, that's good enough for me!

Have been on vaca so just noticed this. Thanks!

**Comment by jerm** [comment]
This was vexing me as well. Just as i finally got around to investigating, i saw your fix and upgraded. Thanks! :-D

**Pull request merged**
